name: Build Realme 5 Pro NetHunter Kernel
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel for rmx1971
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          # Your specific edited kernel source
          kernel-url: https://github.com/mtchary1963-code/RMX1971_kernel_built.git
          kernel-branch: twelve
          config: KharaMe_defconfig
          
          # Architecture & OS
          arch: arm64
          android-version: 12
          
          # Compilers (Pixel Experience 12 requires Clang)
          aosp-gcc: true
          aosp-clang: true
          
          # NetHunter specific flags (Crucial for HID/WiFi)
          nethunter: true
          nethunter-patch: false
          
          # Root & Packaging
          ksu: true
          anykernel3: true
          
